GoSearch with file storage
georgiybykov/gocore pull request #5
Opened 2023-07-12 23:46 UTC by georgiybykov

- Для повторного использования полученных сканером данных требуется сохранить их в файле и восстановить при запуске программы.

2023-07-12 23:49 UTC, georgiybykov commented
LGTM

2023-07-16 15:32 UTC, DmitriyVTitov requested changes
Код сложный, читать и разбираться непросто. А задача весьма простая.
Предлагаю переписать, это важно.

2023-07-16 15:32 UTC, DmitriyVTitov commented on homework-05/cmd/search.go
> +	}
Ошибка не должна игнорироваться никогда!

2023-07-16 15:32 UTC, DmitriyVTitov commented on homework-05/cmd/search.go
> +	error := repository.Push(documents, *lexeme)
Ошибке принято давать имя `err`

2023-07-16 15:32 UTC, DmitriyVTitov commented on homework-05/pkg/repository/repository.go
> +}
Функция называется "фильтр", но при этом она читает что-то из файла и что-то с этим делает. Неочевидные побочные эффекты, нелогичный код.

2023-07-16 15:32 UTC, DmitriyVTitov commented on homework-05/pkg/repository/repository.go
> +}
Тут тоже куча какаих-то действий сведено в функцию с ничего не говорящим именем, без комментарием и т.д.

2023-07-16 15:32 UTC, DmitriyVTitov commented on homework-05/pkg/repository/repository.go
> +	}
`error` - встроенный тип данных для ошибки, имя переменной - `err`

2023-07-17 23:57 UTC, georgiybykov commented
> Код сложный, читать и разбираться непросто. А задача весьма простая. Предлагаю переписать, это важно.

Переписал.

2023-07-21 18:41 UTC, DmitriyVTitov approved these changes
Теперь сильно лучше!
Одно замечание: желательно избегать длинных веток кода в условиях.
То есть надо так: проверить условие, если что-то не так - завершить работу, иначе основной код должен идти не в ветке. И уж тем более желательно избегать `else if`.
Это я про строки 35 и 53 в `search.go`

2023-07-22 16:05 UTC, merged